import Head from "next/head";
import React, { FC } from "react";
import Nav from "./Nav";
import SideBar from "./SideBar";

const index: FC = ({ children }) => {
  return (
    <div className="flex justify-between h-screen bg-gray-200 font-quicksand">
      <Head>
        <title>Create Next App With TW {"&"} TS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <div className=" w-full container overflow-y-scroll no-scroll">{children}</div>
      <SideBar />
    </div>
  );
};

export default index;
